### ISSUE TITLE
Integration of java projects to FDM

### ISSUE THREAD

**Issue by plb7777** [59de44955ebd/FDM-UL#4]
Hi developer,

I have written a java project to analyze link using yt-dlp (https://github.com/plb7777/LinkAnalyzer) , I have also written a software that will merge audio and video files using ffmpeg. 
Please try the software and let me know if you can add such functionality to FDM-UL.

Thanks

**Comment by 59de44955ebd** [comment]
What your "LinkAnalyzer" does is exactly what FDM-UL already does: it calls yt-dlp, and then lists the available download URLs in a combobox. But as I had already explained before, it filters the list returned by yt-dlp and only displays those URLs that FDM-UL can actually download, i.e. only HTTP(S)-URLs, but no streaming links etc.

Merging video and audio files via ffmpeg is trivial in a CMD shell/Powershell, I do this all the time. I don't see any benefit of integrating this into FDM-UL, which is meant to be just a plain downloader. My goal for this "Ultra-Light" version was to remove all the bloat from the original FDM version, so why should I new add new bloat...

But, it's open source, so if you are willing to learn some C/C++, just fork the repo and then add whatever extra functions you desire to your own version.
